content: optimize tailwindcss in angular
notiz-dev/notiz pull request #129
Opened 2020-12-11 16:11 UTC by marcjulian

2020-12-11 16:50 UTC, garygrossgarten commented on content/blog/optimize-tailwindcss-in-angular.md
> +[Tailwind CSS](https://tailwindcss.com) generates a **large amount** of utility classes for your development build by design. For your Angular application you want the best performance by **only** in
By design, [Tailwind CSS](https://tailwindcss.com) generates a **large amount** of utility classes for your development build.

2020-12-11 16:55 UTC, garygrossgarten commented on content/blog/optimize-tailwindcss-in-angular.md
> +You are learning how to [optimize](https://tailwindcss.com/docs/optimizing-for-production) Tailwind CSS in your [Angular](/blog/angular-10-with-tailwindcss) and [Scully](/blog/jamstack-angular-scully
You are going to learn...?

2020-12-11 16:55 UTC, garygrossgarten commented on content/blog/optimize-tailwindcss-in-angular.md
> +The optimizations in this post have been tested with Angular 11 and Tailwind CSS 2.0, also applies for Angular 10 and Tailwind CSS 1.9.x.
???

2020-12-11 16:58 UTC, garygrossgarten commented on content/blog/optimize-tailwindcss-in-angular.md
> +Now run `npm run build:prod` to **only** include used Tailwind CSS utilities in your Angular production build. This works even great in your Scully application.
This even works great in your Scully application

2020-12-11 16:58 UTC, garygrossgarten commented on content/blog/optimize-tailwindcss-in-angular.md
> +To take advantage let's migrate our example from above with `purge` as an array to an object using `content` for your template paths.
to take advantage of ...

2020-12-11 16:59 UTC, garygrossgarten commented on content/blog/optimize-tailwindcss-in-angular.md
> +Now you can purge only specific [layers](https://tailwindcss.com/docs/functions-and-directives#layer), `enabled` it manually, go mad with `mode: 'all'` or pass `options` directly to [PurgeCSS](https:
???

2020-12-11 16:59 UTC, garygrossgarten commented on content/blog/optimize-tailwindcss-in-angular.md
> +Now you can purge only specific [layers](https://tailwindcss.com/docs/functions-and-directives#layer), `enabled` it manually, go mad with `mode: 'all'` or pass `options` directly to [PurgeCSS](https:
enable it manually or go mad?

2020-12-11 17:02 UTC, garygrossgarten commented on content/blog/optimize-tailwindcss-in-angular.md
> +Perfect, now your Angular or Scully applications are optimized for production and you are ready to it to [Firebase Hosting](/blog/firebase-hosting-preview-deploy) or other services.
ready to deploy it ?

2020-12-11 17:02 UTC, garygrossgarten requested changes
see inline comments

2020-12-14 22:38 UTC, marcjulian commented
Update the content :)

2020-12-14 23:25 UTC, garygrossgarten approved these changes
👏

2020-12-15 08:06 UTC, merged